# Generated by Django 4.1.1 on 2022-10-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_provider', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('contact_number', models.BigIntegerField()),
            ],
        ),
    ]
