# Generated by Django 4.1.1 on 2022-10-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='catogary',
            name='img',
            field=models.ImageField(default='NA', upload_to='images/'),
        ),
    ]
