# Generated by Django 4.1.1 on 2022-10-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_catogary_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='myapp.queries'),
        ),
    ]
