# Generated by Django 4.1.1 on 2022-10-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='content',
            field=models.TextField(default='na', max_length=180),
        ),
    ]
