# Generated by Django 4.1.1 on 2022-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_queries_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='content',
            field=models.CharField(default='na', max_length=180),
        ),
    ]
