# Generated by Django 4.1.1 on 2022-10-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_queries_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='Query_detail',
            field=models.CharField(max_length=180),
        ),
    ]
