# Generated by Django 4.1.1 on 2022-10-10 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_alter_queries_query_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceQuery',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Query_Detail', models.TextField()),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.services')),
                ('parant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.servicequery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
