# Generated by Django 4.1.1 on 2022-10-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_servicequery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='content',
        ),
    ]
