# Generated by Django 4.1.1 on 2022-10-23 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_queries_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='Query_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.services'),
        ),
    ]
